// var age = prompt("how old are you?")

// if(age >= 18){
//     console.log("welcome")
// }
// else{
//     console.log("you are under age")
// }

// var age = prompt("how old are you?")

// while(age == 20){
//     console.log("welcome")
//     age = false
// }

var myCars = 0
while (myCars < 10){
    console.log("counting ")
    myCars++
}
alert("you have 10 cars!!!")

for (var myCars = 0; myCars <= 10; myCars++){
    console.log("counting " + myCars)
}

alert("you have 10 cars!!!")