var myPerson = {
    "age": 100,
    "eyeColor": "Blue",
    "height": "6'5"
    
};

myPerson["myCars"] = ["BMW" , "AUDI" , "MERC"]


var myFam = {
  "mom": {
    age: 45,
    height: "5'4",
    eyeColor: "brown",
    },

  "dad": {
     age: 47,
    height: "5'8",
    eyeColor: "brown",
    },

  "brother": {
    age: 22,
    height: "5'9",
    eyeColor: "brown",
    favCars: ["BMW", "AUDI", "TESLA"]
    }
 };