var condition = 6;

if ( condition > 4 ) {
    console.log( condition + " is larger than 4. ")
} else {
    console.log(condition+ " is not greater than 4")
}

var car = "toyota";

if (car.length > 3){
    console.log(car.length + " is larger than 3")
} else {
    console.log(car.lenght + "is not greater than 3")
}

var variable = "dog"

console.log(variable.length)


var lemonChicken = false;
var beefWithBlackBean = true;
var sweetAndSourPork = true;

if (lemonChicken) {
  console.log("Great! I'm having lemon chicken!");
} else if (beefWithBlackBean) {
  console.log("I'm having the beef.");
} else if (sweetAndSourPork) {
  console.log("OK, I'll have the pork.");
} else {
  console.log("Well, I guess I'll have rice then.");
}

var mom = false;
var dad= true;
var tom = false
if (mom){
  console.log("hello mom");
} else if (tom){
  console.log("hello stranger.")
} else if (dad){
  console.log("hello dad")
}

