var arsenal ={
    "captain":"MO",
"starPlayer": "Saka",
"numberTitles": 7
}

arsenal["manager"] = "mikel";

var myPets = [
    {"name" : "alex", "animal" : "dog", "food" : ["dog food", "cat food"]},
    {"name" : "jon", "animal" : "dog"}
];

console.log(myPets[0].food[0]);

var realMadrid ={
    "cl" : 15,
    "titles" : 31

}
    

var game = [
    { name : "Odwa", score : 0 },
    { name : "Leon", score : 0 },
    { name : "Lihle", score : 10 }

]

console.log(game[0].name)


    